### ISSUE TITLE
How would you automate updating vscode extensions?

### ISSUE THREAD

**Issue by hydrajump** [nix-community/nix4vscode#13]
I'm considering using this project instead of the old extensions packaged in nixpkgs in my home-manager standalone config.

It seems that the steps to update the extensions would look like this:  

1. `nix flake update`
2. Get the `rev` of `nixpkgs` from the `flake.lock`
3. Find the latest vscode version using the nixpkgs rev from step 2:
`https://github.com/NixOS/nixpkgs/blob/e92039b55bcd58469325ded85d4f58dd5a4eaf58/pkgs/applications/editors/vscode/vscode.nix#L43`
4. Update `vscode_version` in `config.toml` with version from step 3
5. Get the latest vscode extensions for the version in step 4, `cargo run -- config.toml`
6. Update home manager config `home-manager switch --flake .`

Is there a more  convenient way to do this?

**Comment by cathaysia** [comment]
Generally speaking, I rarely update the entire flake.lock. I will update vscode extension regularly. This step is completed through github actions.

**Comment by cathaysia** [comment]
just like this:

```yaml
name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly install --git https://github.com/cathaysia/nix4vscode
      - name: Update vscode extension
        run: |
          bash -c 'cd home/dot_config/home-manager && nix flake update "nix-vscode-extensions"'
          bash -c 'nix4vscode home/dot_config/home-manager/config.toml -o home/dot_config/home-manager/config/vscode_plugins.nix'
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: bot
          author_email: somebody@email.com
          commit: --signoff
          message: "feat(vscode): Update vscode extension"
```
